"""add description to products

Revision ID: e6489801cc5f
Revises: 18f1a7d58796
Create Date: 2026-05-02 12:09:05.844657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6489801cc5f'
down_revision: Union[str, Sequence[str], None] = '18f1a7d58796'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'products',
        sa.Column('description', sa.String(length=500), nullable=True))
    op.execute("Update products SET description = 'No description'")
    op.alter_column('products', 'description', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
